action_id: trunk-cache-prune
date: 2024-02-05 07:19:56
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Filesystem error: in current_path: call to getcwd failed: operation not permitted\x1b[0m\n"
  err: "shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted\n"
timestamp: 1707117596
full_timestamp:
  nanos: 165821000
  seconds: 1707117596
trunk_version: 1.19.0
