action_id: trunk-upgrade-available
date: 2024-02-11 18:21:39
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Filesystem error: in current_path: call to getcwd failed: operation not permitted\x1b[0m\n"
  err: "shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted\n"
timestamp: 1707675699
full_timestamp:
  nanos: 592738000
  seconds: 1707675699
trunk_version: 1.19.0
