action_id: trunk-upgrade-available
date: 2024-01-30 17:54:40
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Filesystem error: in current_path: call to getcwd failed: operation not permitted\x1b[0m\n"
  err: "shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted\n"
timestamp: 1706637280
full_timestamp:
  nanos: 601350000
  seconds: 1706637280
trunk_version: 1.19.0
