action_id: trunk-share-with-everyone
date: 2024-02-10 06:36:02
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Filesystem error: in current_path: call to getcwd failed: operation not permitted\x1b[0m\n"
  err: "shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted\n"
timestamp: 1707546962
full_timestamp:
  nanos: 922894000
  seconds: 1707546962
trunk_version: 1.19.0
